### ISSUE TITLE
Broken pipe

### ISSUE THREAD

**Issue by alem0lars** [mhartington/nvim-typescript#108]
# Problems summary

I'm getting the following error:

```
BrokenPipeError: [Errno 32] Broken pipe
error caught in async handler '/etc/xdg/nvim/cache/vimplug/nvim-typescript/rplugin/python3/nvim_typescript:function:TSOnBufEn
ter [[]]'
Traceback (most recent call last):
  File "/etc/xdg/nvim/cache/vimplug/nvim-typescript/rplugin/python3/nvim_typescript/__init__.py", line 640, in on_bufenter
    self._client.open(self.relative_file())
  File "/etc/xdg/nvim/cache/vimplug/nvim-typescript/rplugin/python3/nvim_typescript/client.py", line 206, in open
    self.send_command("open", args)
  File "/etc/xdg/nvim/cache/vimplug/nvim-typescript/rplugin/python3/nvim_typescript/client.py", line 187, in send_command
    self.__write_to_server(request)
  File "/etc/xdg/nvim/cache/vimplug/nvim-typescript/rplugin/python3/nvim_typescript/client.py", line 132, in __write_to_serve
r
    Client.server_handle.stdin.write(serialized_request)
```

## Expected

Shouldn't get any error.

## Environment Information

NVIM v0.2.0
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-pc-linux-gnu-gcc -O2 -pipe -march=native -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DD
Compiled by root@kate

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "/etc/vim/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

## Provide a minimal vim rc with less than 50 lines (Required!)

```vim
set runtimepath+=~/path/to/nvim-typescript
```

## The reproduce ways from neovim starting

 1. Open typescript file
 2. As soon as you open the file it gives those errors

**Comment by mhartington** [comment]
Can you run `UpdateRemotePlugins`

**Comment by alem0lars** [comment]
I already did it.

This is the output:

```
remote/host: python3 host registered plugins ['denite', 'deoplete', 'far', 'iron', 'nvim_typescript']
remote/host: python host registered plugins ['floobits']
remote/host: generated rplugin manifest: /home/alem0lars/.local/share/nvim/rplugin.vim
```

**Comment by d0m3nik** [comment]
I encountered the same problem. Make sure you have installed `tsserver`:
`sudo npm install -g typescript`
It would be nice to have this in the "Prerequisites" section of the readme.

**Comment by mhartington** [comment]
@d0m3nik it is, it's in the docs.

https://github.com/mhartington/nvim-typescript/blob/master/doc/nvim-typescript.txt#L26

Please be sure to read it over. Though it is slightly out of date, as you dont need typescript installed globally, as you could have typescript installed locally for a project.

**Comment by d0m3nik** [comment]
@mhartington Oh, I overlooked that. Thanks for pointing it out.
When installing I just followed the description on the github page. I thought adding it to:
https://github.com/mhartington/nvim-typescript/blob/master/README.md#L14
might be a good idea

**Comment by mhartington** [comment]
@alem0lars Im still unable to reproduce this. If you could find a way to reproduce this error again, please open up a new issue. Thanks!

**Comment by tooke7** [comment]
I'm getting the same error:

```
error caught in async handler '/home/jobryant/.config/nvim/plugged/nvim-typescript/rplugin/python3/nvim_typescript:function:TSOnBufEnter [[]]'                                                                       
Traceback (most recent call last):
  File "/home/jobryant/.config/nvim/plugged/nvim-typescript/rplugin/python3/nvim_typescript/__init__.py", line 689, in on_bufenter
    self._client.open(self.relative_file())
  File "/home/jobryant/.config/nvim/plugged/nvim-typescript/rplugin/python3/nvim_typescript/client.py", line 220, in open
    self.send_command("open", args)
  File "/home/jobryant/.config/nvim/plugged/nvim-typescript/rplugin/python3/nvim_typescript/client.py", line 201, in send_command
    self.__write_to_server(request)
  File "/home/jobryant/.config/nvim/plugged/nvim-typescript/rplugin/python3/nvim_typescript/client.py", line 147, in __write_to_server
    Client.server_handle.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe
'''

It doesn't happen as soon as I open a typescript file, but at some point while editing the error gets triggered. Then it happens whenever I open a new typescript file or try to execute a typescript command (e.g. TSType). Opening and closing vim fixes it (until the error gets triggered again).

It happens pretty consistently for me. I'll see if I can find an exact way to reproduce it.

**Comment by tooke7** [comment]
Actually it looks like the problem is with tsserver. It seems to keep dying. Running TSStart fixes the error without having to restart neovim. I was using tsuquyomi with regular vim but it had bad reliability problems; I assumed it was a problem with tsuquyomi but perhaps not. Hopefully at some point I'll find out the root problem, but for now running TSStart manually is an acceptable workaround.

**Comment by mhartington** [comment]
Hmm, I wonder what could be causing it. Again, Im not able to replicate this at all in my test. If you could provide some sort of sample project that has the issue, I could look

**Comment by tooke7** [comment]
Thanks, I'll see what I can do. I'm seeing the problem while working on a large closed-source project, but I'll see if it happens on a small test project.

**Comment by mhartington** [comment]
@tooke7 yeah, the smaller the project the better. Let me test a few things out for a proper logging system so we can get an idea of whats going on. I'll keep you posted.

**Comment by mhartington** [comment]
I just pushed some initial logging features for tsserver

Try 

```
  let g:nvim_typescript#debug_enabled = 1
```

**Comment by tooke7** [comment]
One of my coworkers suggested that the root problem may be tsserver is running out of memory since our code base is so large. In any case, tsserver is crashing for some reason. I was able to simulate the error like so:

1. Open typescript file in nvim
2. Kill tsserver (e.g. `ps aux | grep tsserver; kill <tsserver pid>`)
3. Run any nvim-typescript command. e.g. switching to a different buffer gives the following:

```
error caught in async handler '/home/jobryant/.config/nvim/plugged/nvim-typescript/rplugin/python3/nvim_typescript:function:TSOnBufEnter [[]]'                                                                       
Traceback (most recent call last):
  File "/home/jobryant/.config/nvim/plugged/nvim-typescript/rplugin/python3/nvim_typescript/__init__.py", line 690, in on_bufenter
    self._client.open(self.relative_file())
  File "/home/jobryant/.config/nvim/plugged/nvim-typescript/rplugin/python3/nvim_typescript/client.py", line 223, in open
    self.send_command("open", args)
  File "/home/jobryant/.config/nvim/plugged/nvim-typescript/rplugin/python3/nvim_typescript/client.py", line 204, in send_command
    self.__write_to_server(request)
  File "/home/jobryant/.config/nvim/plugged/nvim-typescript/rplugin/python3/nvim_typescript/client.py", line 150, in __write_to_server
    Client.server_handle.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe
```

(There wasn't anything about the error in the debug log by the way.)

Closing and opening vim fixes the problem (running TSStart doesn't; I don't know why that was working for me before). I'd say you could close this issue if you want since the real error is with tsserver. But if you think it's a good idea, nvim-typescript could check to see if tsserver is running before executing any commands and then start it again if necessary, instead of only starting tsserver when you open vim.

**Comment by pyrho** [comment]
Hi @tooke7 ,

Maybe the issue reported [here](https://github.com/Microsoft/TypeScript/issues/18055) is relevant to your case.
Could you try spawning `tsserver` from this plugin with the `--max_old_space_size=4096` command line switch.

If it fixes your issue, we could consider making it an option of nvim-typescript.

**Comment by tooke7** [comment]
I've added the flag. The server still crashes, but I think it may be crashing less frequently (hard to tell; could also just be confirmation bias).

**Comment by mhartington** [comment]
Closing as part of house keeping. I cannot replicate locally. Please open a new issue if the problem is still around.

**Comment by oliver-nh** [comment]
Note, was also getting this error. Upgrading typescript seems to have fixed it (no idea why). Will post here if it resurfaces.

**Comment by mDibyo** [comment]
@oliver-nh Which version of typescript did you upgrade to?

**Comment by olivercodes** [comment]
@mDibyo pretty sure it was 2.6.2 or 2.7.2. I can double check in the morning.
